sudo: required
language: scala
scala:
- 2.10.6
jdk:
- oraclejdk8

env:
  matrix:
    - SBT_CMD="scripted sbt-dotenv/check-load-dot-env"
    - SBT_CMD="scripted sbt-dotenv/check-skip-invalid-lines"

script:
  # It doesn't need that much memory because compile and run are forked
  - sbt -J-XX:ReservedCodeCacheSize=128m -J-Xmx800M -J-Xms800M -J-server "$SBT_CMD"
