dist: trusty
language: scala

# Use container-based infrastructure
sudo: false

env:
  global:
    - secure: glhEB9krKsLbmcoQ5l6uDPGX+WWYThNwK24eUFkqutnum2avk98Z3e5sXtldDR386E1GSaDZYzWE8rv0AF9Xdqz4MvnZ/ZK11DtUfvWt9Vrd/NhsV081Mks3iJsyq9rqxk0byazUCuosuCnRTr4jzSE5LrGp2w7Fe1C/yKETYTc=
    - secure: LSz3qTRwykG5moCbWZoDH0eDu4EKEg89N3imxdGJfSrsX/iFpVKtFWfhk78vqBnJYj34H8jfNsm7v4ar8r4QFAXUGVrwAIBDcHuTDVphYBqwLdeImINb9gmUefOwg8z3aFqjkrnxts3U01K4Iuk1R5V6zTsBv5bXIp55/squ1oA=

before_install:
  - git fetch --tags

matrix:
  include:
    - env: SBT_VERSION=1.3.13
      jdk: openjdk8
    - env: SBT_VERSION=0.13.18
      jdk: openjdk8
    - env: SBT_VERSION=1.3.13
      jdk: openjdk11

script:
  - sbt ^^$SBT_VERSION clean test scripted
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

deploy:
  provider: script
  script: sbt ^^$SBT_VERSION ci-release
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9].* and $SBT_VERSION = 1.3.13
    branch: master
    jdk: openjdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/
